sources:
  - name: spectre
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/33075/spectre-preview/0.0.5
        # endpoint: http://127.0.0.1:8000/subgraphs/name/spectre

codegen:
  strictScalars: true
  immutableTypes: true
  useTypeImports: false # import name conflict if set to true
  dedupeFragments: true
  scalars:
    BigDecimal: string
    BigInt: bigint
    Bytes: string

documents:
  - ./src/spectre-subgraph-queries.graphql
