sources:
  - name: spectre
    handler:
      graphql:
        # endpoint: http://127.0.0.1:8000/subgraphs/name/spectre
        endpoint: https://api.thegraph.com/subgraphs/name/bpierre/spectre-preview

documents:
  - ./src/spectre-subgraph-queries.graphql
