[build.environment]
  NODE_VERSION = "16"
  PYTHON_VERSION = "3.9"
  NPM_FLAGS = "--prefix=/dev/null"
[build]
  publish = "pkg/website/dist/"
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm website:build"
