[build.environment]
  NODE_VERSION = "16"
  PYTHON_VERSION = "3.8"
  NPM_FLAGS = "--version && echo 'just a test'"
[build]
  publish = "pkg/website/dist/"
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm website:build"
